#
# Copyright (c) 2021-2022 Richard <https://sveil.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/sveil/Actions-SveilOS
# Description: Build SveilOS Arm64 using GitHub Actions
#
name: Build SveilOS Arm64

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Ubuntu version"
        required: false
        default: "20.04.0"

jobs:
  build_job:
    # The host should always be Linux
    runs-on: ubuntu-20.04
    name: Build on ubuntu-20.04 aarch64
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Build artifact
        uses: uraimo/run-on-arch-action@v2.0.9
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu20.04

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}

          # Set an output parameter `uname` for use in subsequent steps
          run: |
            uname -a
            echo ::set-output name=uname::$(uname -a)

      - name: Get the output
        # Echo the `uname` output parameter from the `runcmd` step
        run: |
          echo "The uname output was ${{ steps.runcmd.outputs.uname }}"
